name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.x"

      - name: Install dependencies
        run: |
          npm ci

      - name: lint check
        run: |
          npm run lint

      - name: Build
        env:
          BASE_URL: /demodam/
        run: |
          npm run build

      - name: Deployment to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: public/
